export const CONTENT = {
  tr: {
    nav: {
      home: "Ana sayfa",
      current: "Şu an",
      routine: "Rutin",
      mindMap: "Harita",
      projects: "Lab",
      roadmap: "Hedefler",
      geek: "Geek Mode",
      contact: "İletişim",
      language: "EN",
    },
    phaseLabels: {
      Sabah: "Sabah",
      Öğle: "Öğle",
      Akşam: "Akşam",
      Gece: "Gece",
    },
    hero: {
      eyebrow: "~/balıkesir-üni/bilgisayar-müh",
      greeting: "Selam, ben",
      typed: "Halil",
      body: "Balıkesir Üniversitesi'nde Bilgisayar Mühendisliği okuyorum. Kodun sadece ekranda görünen kısmıyla değil, arkasındaki mantıkla da ilgileniyorum; bazen bir devreyi söküp inceliyor, bazen bir oyunun sistemlerini kurcalıyor, bazen de düzenli antrenmanla kafamı resetliyorum.",
      scroll: "Bir günümü keşfetmek için kaydırın",
      cards: [
        {
          key: "code",
          title: "Kod",
          body: "Python, Java, C# ve web tarafında yeni şeyler denemeyi seviyorum.",
        },
        {
          key: "hardware",
          title: "Donanım",
          body: "Bozuk bir cihazı açıp 'bunun içinde ne dönüyor?' diye bakmak ayrı keyif.",
        },
        {
          key: "games",
          title: "Oyun Evrenleri",
          body: "Hikayeli oyunlar, MMORPG dünyaları ve Minecraft sistemleri favori alanım.",
        },
        {
          key: "balance",
          title: "Denge",
          body: "Kod, oyun, kitap, dizi/film ve antrenman arasında kendi düzenimi kuruyorum.",
        },
      ],
    },
    current: {
      status: "status: online",
      title: "Şu An Ne Yapıyorum?",
      cards: [
        {
          tag: "gündem",
          key: "flame",
          title: "Finallerle savaş modu",
          body: "Nümerik Analiz, Ayrık Matematik, Fizik 2… Kısa vadeli görev: dönemi temiz kapatmak.",
        },
        {
          tag: "odak",
          key: "target",
          title: "Bu portfolio sitesini parlatıyorum",
          body: "Renk geçişleri, sabit menü, TR/EN dil seçeneği ve küçük etkileşimlerle daha karakterli hale getiriyorum.",
        },
        {
          tag: "oyun",
          key: "gamepad",
          title: "Hikaye + MMORPG kafası",
          body: "İyi yazılmış karakterler, keşif hissi ve uzun vadeli gelişim sistemi olan oyunlar ekstra ilgimi çekiyor.",
        },
        {
          tag: "okuma",
          key: "book",
          title: "Kitap listesi büyüyor",
          body: "Kendimi geliştirecek, bakış açımı açacak veya iyi bir dünyaya sokacak kitaplara yer açıyorum.",
        },
        {
          tag: "izleme",
          key: "film",
          title: "Dizi / film molaları",
          body: "Yoğun günlerin arasında kafayı dağıtacak iyi hikayeleri ve kaliteli evrenleri takip ediyorum.",
        },
        {
          tag: "kurcalama",
          key: "wrench",
          title: "Donanım & Minecraft deneyleri",
          body: "Bozulan gamepad'leri hayata döndürmek ya da Minecraft'ta sistemi sistem yapan detayları kurcalamak.",
        },
      ],
    },
    routine: {
      eyebrow: "Bir Günüm",
      title: "Sabahtan Geceye Rutinim",
      detailOpen: "Detayları gör",
      detailClose: "Daha az göster",
      items: [
        {
          time: "08:00",
          title: "Güne reset atmak",
          key: "heart",
          body: "Sabah tarafında düzenli kalmaya çalışıyorum. Bazen antrenman, bazen kısa bir plan, bazen de sadece güne sağlam başlama meselesi.",
          details: [
            "Planlı antrenman ve ilerleme takibi",
            "Enerjiyi toparlayan basit sabah rutini",
            "Günün ana görevlerini netleştirme",
          ],
        },
        {
          time: "13:00",
          title: "Kod, ders ve kurcalama saati",
          key: "cog",
          spin: true,
          body: "Günün teknik tarafı burada başlıyor: dersler, web denemeleri, donanım merakı ve bazen Minecraft mantık sistemleri.",
          details: [
            "Python, Java, C# ve web geliştirme denemeleri",
            "Gamepad / elektronik cihaz tamiri",
            "Redstone ve oyun içi otomasyon mantıkları",
          ],
        },
        {
          time: "19:00",
          title: "Hikaye, öğrenme ve sakinleşme",
          key: "sparkles",
          body: "Akşamları biraz daha kişisel taraf: kitap, dizi/film, oyun evrenleri, diksiyon ve uzun vadeli hedefler.",
          details: [
            "Kitap, dizi/film ve hikayeli oyun takibi",
            "Diksiyon ve iletişim becerileri egzersizleri",
            "Finansal okuryazarlık ve teknoloji gündemi",
          ],
        },
      ],
    },
    mindMap: {
      eyebrow: "ilgi haritası",
      title: "Beynimin Küçük Haritası",
      body: "Beni tek bir başlıkla anlatmak zor. Kod, donanım, oyunlar, hikayeler ve öğrenme merakı birbirine bağlanınca ortaya böyle bir harita çıkıyor. Düğümlere tıklayarak detayları keşfedebilirsin.",
      panelLabel: "seçili düğüm",
      nodes: [
        {
          key: "code",
          title: "Kod",
          body: "Web arayüzleri, algoritma mantığı ve bir fikri çalışan bir şeye dönüştürme kısmı beni en çok çeken taraflardan biri.",
          tags: ["JavaScript", "React", "Python", "C#"],
        },
        {
          key: "hardware",
          title: "Donanım",
          body: "Breadboard, devre, gamepad tamiri ve cihazların içini merak etme tarafı yazılımla birleşince daha eğlenceli oluyor.",
          tags: ["devre", "tamir", "sensör", "kurcalama"],
        },
        {
          key: "games",
          title: "Oyunlar",
          body: "Hikayeli oyunlar ve MMORPG yapıları ilgimi çekiyor; çünkü iyi sistem tasarımı, ilerleme hissi ve dünya kurma tarafı çok güçlü.",
          tags: ["MMORPG", "story", "quest", "progression"],
        },
        {
          key: "stories",
          title: "Kitap / Dizi / Film",
          body: "İyi yazılmış karakterleri, sağlam evrenleri ve insanı içine çeken hikayeleri seviyorum. Bu taraf sitedeki kişisel tonu da besliyor.",
          tags: ["evren", "karakter", "hikaye", "bakış açısı"],
        },
        {
          key: "tinkering",
          title: "Kurcalama",
          body: "Bir şeyi sadece kullanmak değil, nasıl çalıştığını anlamak daha keyifli. Bazen kodda, bazen devrede, bazen oyunun sistemlerinde.",
          tags: ["debug", "deney", "redstone", "not alma"],
        },
        {
          key: "balance",
          title: "Halil",
          body: "Merkezde tek bir şey yok; öğrenmek, denemek, oyunlardan ilham almak ve kendimi adım adım geliştirmek var.",
          tags: ["öğren", "üret", "geliş", "tekrar"],
        },
      ],
    },
    projects: {
      eyebrow: "Lab Alanı",
      title: "Projeler ve Fikirler",
      body: "Burası bitmiş projeler vitrini gibi değil; daha çok öğrendiklerimi, denemelerimi ve ileride büyütebileceğim fikirleri tuttuğum küçük bir üretim alanı.",
      tooltipIntro: "Etiketlerin üzerine gelerek kısa teknoloji notlarını görebilirsin.",
      items: [
        {
          status: "yayında",
          title: "Kişisel Portfolio v1",
          key: "layout",
          visual: "interface",
          body: "Kaydırıldıkça renk değiştiren, TR/EN destekli, sabit menülü ve geek mode'lu kişisel web sitesi. İlk amaç: kendimi daha iyi anlatmak.",
          tags: ["Next.js", "React", "Tailwind", "JavaScript"],
        },
        {
          status: "fikir",
          title: "Oyun / Kitap / Dizi Günlüğü",
          key: "library",
          visual: "game",
          body: "Oynadığım, okuduğum ve izlediğim şeyleri puan, not ve kategoriyle takip edebileceğim küçük bir kişisel arşiv fikri.",
          tags: ["UI", "LocalStorage", "Veri Modeli"],
        },
        {
          status: "fikir",
          title: "Donanım Tamir Notları",
          key: "wrench",
          visual: "circuit",
          body: "Gamepad veya küçük elektronik tamirlerinde yapılan işlemleri adım adım not alan, hata-sebep-çözüm mantığında mini bir kayıt sistemi.",
          tags: ["Donanım", "Dokümantasyon", "Arşiv"],
        },
        {
          status: "sonra",
          title: "AGNO / Ders Takip Aracı",
          key: "calculator",
          visual: "interface",
          body: "Ders, kredi ve not bilgilerini düzenli tutup dönem hedefini daha net görmeyi sağlayacak basit ama kullanışlı bir öğrenci aracı.",
          tags: ["JavaScript", "Form", "Hesaplama"],
        },
      ],
    },
    roadmap: {
      eyebrow: "quest log",
      title: "Gelecek Hedefleri",
      body: "Bir geliştirici yol haritası gibi: tamamlanmayı bekleyen görevler, açılacak yetenekler ve uzun vadeli boss savaşları.",
      active: "aktif",
      locked: "kilitli",
      quests: [
        {
          span: "kısa vadeli",
          status: "aktif",
          key: "book",
          title: "Web tarafını güçlendirmek",
          body: "Next.js, veri tabanı, API mantığı ve temiz arayüz tarafında daha sağlam işler çıkarmak.",
        },
        {
          span: "kısa vadeli",
          status: "aktif",
          key: "zap",
          title: "İngilizce ve iletişim kasmak",
          body: "Teknik bilgiyi sadece bilmek değil, iyi anlatabilmek de önemli. Diksiyon ve İngilizce burada devrede.",
        },
        {
          span: "orta vadeli",
          status: "aktif",
          key: "cpu",
          title: "Donanım + yazılım mini proje",
          body: "Fiziksel bir cihazı yazılımla kontrol eden küçük ama gerçek çalışan bir sistem kurmak.",
        },
        {
          span: "orta vadeli",
          status: "kilitli",
          key: "gamepad",
          title: "Kişisel takip uygulaması",
          body: "Oyun, kitap, dizi/film ve hedefleri tek yerde takip edeceğim küçük bir dashboard yapmak.",
        },
        {
          span: "uzun vadeli",
          status: "kilitli",
          key: "rocket",
          title: "Gerçek kullanıcıya dokunan ürün",
          body: "Sadece demo değil; baştan sona tasarlanmış, kullanılabilir ve yayınlanmış bir proje çıkarmak.",
        },
        {
          span: "uzun vadeli",
          status: "kilitli",
          key: "trophy",
          title: "Açık kaynak ve ekip deneyimi",
          body: "Toplulukla üretmek, kod kalitesini yükseltmek ve gerçek ekip süreçlerine daha çok girmek.",
        },
      ],
    },
    geek: {
      eyebrow: "mini terminal",
      title: "Geek Mode'u Aç",
      body: "Sitenin ana akışını bozmayan küçük bir terminal alanı. Birkaç komutla hakkımda kısa bilgiler, beceriler ve iletişim detayları görülebilir.",
      buttonOn: "geek mode: on",
      buttonOff: "geek mode: off",
      terminalLabel: "Geek mode terminali",
      terminalTitle: "halil@portfolio: ~",
      close: "Terminali kapat",
      bootLines: [
        "$ sudo ./geek_mode --activate",
        "[ ok ] kahve seviyesi kontrol ediliyor... yeterli",
        "[ ok ] redstone devreleri yükleniyor...",
        "[ ok ] MMORPG görev günlüğü açılıyor...",
        "[ ok ] kitap / dizi / film listesi senkronize edildi.",
        "[ ok ] gamepad sürücüleri bağlanıyor...",
        "> merhaba, dünya. ben Halil.",
        "> kod yaz, kurcala, öğren, geliştir, tekrarla.",
        "geek_mode: ONLINE ✓",
      ],
      commands: {
        placeholder: "komut yaz: help",
        list: ["help", "whoami", "skills --list", "ls projects", "cat about.txt", "contact", "clear", "sudo hire-me"],
        unknown: "Komut bulunamadı. Küçük ipucu: help yazmayı dene.",
        responses: {
          help: "Komutlar: help, whoami, skills --list, ls projects, cat about.txt, contact, clear, sudo hire-me",
          whoami: "Halil Efe Kutlu — Bilgisayar Mühendisliği öğrencisi. Kod, donanım, hikayeli oyunlar ve yeni şeyler kurcalama modu açık.",
          "skills --list": "JavaScript / React / Next.js / Tailwind / Python / Java / C# / temel donanım merakı / problem çözme",
          "ls projects": "portfolio-v1  game-book-series-journal.idea  hardware-repair-notes.idea  gpa-tracker.later",
          "cat about.txt": "Klasik CV gibi değil; daha çok öğrenen, deneyen, hata alınca debuglayan ve sonunda bir şeyleri çalıştırmayı seven biri.",
          contact: "WhatsApp butonu sağ altta. Mail: halilefekutlu01@gmail.com",
          "sudo hire-me": "permission granted: Halil quest'e katıldı. Bonus özellik: hızlı öğrenme + kurcalama enerjisi.",
        },
      },
    },
    contact: {
      eyebrow: "İletişim",
      title: "Birlikte bir şeyler yapalım",
      body: "Yeni fikirler, iş birlikleri, proje konuşmaları veya sadece bir merhaba için buradayım.",
      email: "E-posta Gönder",
      copyright: "Halil Efe Kutlu · Balıkesir Üniversitesi",
      backToTop: "Yukarı çık",
    },
    whatsapp: {
      label: "WhatsApp ile yaz",
      text: "Merhaba Halil, siten üzerinden yazıyorum.",
    },
  },
  en: {
    nav: {
      home: "Home",
      current: "Now",
      routine: "Routine",
      mindMap: "Map",
      projects: "Lab",
      roadmap: "Goals",
      geek: "Geek Mode",
      contact: "Contact",
      language: "TR",
    },
    phaseLabels: {
      Sabah: "Morning",
      Öğle: "Noon",
      Akşam: "Evening",
      Gece: "Night",
    },
    hero: {
      eyebrow: "~/balikesir-university/computer-engineering",
      greeting: "Hi, I'm",
      typed: "Halil",
      body: "I study Computer Engineering at Balıkesir University. I care not only about what code shows on the screen, but also about the logic behind it; sometimes I take hardware apart, sometimes I explore game systems, and sometimes I reset my head with a consistent training routine.",
      scroll: "Scroll to explore a day in my life",
      cards: [
        {
          key: "code",
          title: "Code",
          body: "I like trying new things with Python, Java, C# and modern web development.",
        },
        {
          key: "hardware",
          title: "Hardware",
          body: "Opening a broken device and asking 'what is going on inside?' is part of the fun.",
        },
        {
          key: "games",
          title: "Game Worlds",
          body: "Story-driven games, MMORPG worlds and Minecraft systems are my comfort zone.",
        },
        {
          key: "balance",
          title: "Balance",
          body: "I build my own rhythm between code, games, books, series/movies and training.",
        },
      ],
    },
    current: {
      status: "status: online",
      title: "What Am I Doing Now?",
      cards: [
        {
          tag: "agenda",
          key: "flame",
          title: "Finals battle mode",
          body: "Numerical Analysis, Discrete Mathematics, Physics 2… Short-term quest: finish the semester cleanly.",
        },
        {
          tag: "focus",
          key: "target",
          title: "Polishing this portfolio",
          body: "Color transitions, fixed navigation, TR/EN language support and small interactions to make it feel more personal.",
        },
        {
          tag: "games",
          key: "gamepad",
          title: "Story + MMORPG mindset",
          body: "Well-written characters, exploration and long-term progression systems always catch my attention.",
        },
        {
          tag: "reading",
          key: "book",
          title: "The reading list is growing",
          body: "I make room for books that improve me, expand my perspective or pull me into a strong world.",
        },
        {
          tag: "watching",
          key: "film",
          title: "Series / movie breaks",
          body: "Between intense days, I follow good stories and well-built worlds to clear my head.",
        },
        {
          tag: "tinkering",
          key: "wrench",
          title: "Hardware & Minecraft experiments",
          body: "Bringing broken gamepads back to life or exploring the tiny details that make Minecraft systems work.",
        },
      ],
    },
    routine: {
      eyebrow: "A Day In My Life",
      title: "From Morning to Night",
      detailOpen: "Show details",
      detailClose: "Show less",
      items: [
        {
          time: "08:00",
          title: "Resetting the day",
          key: "heart",
          body: "In the morning I try to stay structured. Sometimes it is training, sometimes a short plan, sometimes just starting the day properly.",
          details: [
            "Planned training and progress tracking",
            "A simple morning routine to regain energy",
            "Clarifying the main tasks of the day",
          ],
        },
        {
          time: "13:00",
          title: "Code, classes and tinkering",
          key: "cog",
          spin: true,
          body: "The technical side of the day starts here: classes, web experiments, hardware curiosity and sometimes Minecraft logic systems.",
          details: [
            "Python, Java, C# and web development experiments",
            "Gamepad / electronic device repairs",
            "Redstone and in-game automation logic",
          ],
        },
        {
          time: "19:00",
          title: "Stories, learning and cooling down",
          key: "sparkles",
          body: "Evenings are more personal: books, series/movies, game worlds, diction practice and long-term goals.",
          details: [
            "Books, series/movies and story-driven games",
            "Diction and communication exercises",
            "Financial literacy and technology agenda",
          ],
        },
      ],
    },
    mindMap: {
      eyebrow: "interest map",
      title: "A Small Map of My Mind",
      body: "It is hard to describe me with one title. Code, hardware, games, stories and curiosity connect with each other, so this map gives a more honest picture. Click the nodes to explore the details.",
      panelLabel: "selected node",
      nodes: [
        {
          key: "code",
          title: "Code",
          body: "Web interfaces, algorithmic thinking and turning an idea into something that actually works are some of the parts I enjoy most.",
          tags: ["JavaScript", "React", "Python", "C#"],
        },
        {
          key: "hardware",
          title: "Hardware",
          body: "Breadboards, circuits, gamepad repairs and wondering what is inside a device become more fun when they meet software.",
          tags: ["circuit", "repair", "sensor", "tinkering"],
        },
        {
          key: "games",
          title: "Games",
          body: "Story-driven games and MMORPG structures catch my attention because they combine system design, progression and worldbuilding.",
          tags: ["MMORPG", "story", "quest", "progression"],
        },
        {
          key: "stories",
          title: "Books / Series / Movies",
          body: "I enjoy well-written characters, strong worlds and stories that pull you in. This side also feeds the personal tone of the site.",
          tags: ["worlds", "characters", "story", "perspective"],
        },
        {
          key: "tinkering",
          title: "Tinkering",
          body: "Using something is fine, but understanding how it works is more satisfying; sometimes in code, sometimes in circuits, sometimes in game systems.",
          tags: ["debug", "experiment", "redstone", "notes"],
        },
        {
          key: "balance",
          title: "Halil",
          body: "There is not just one thing in the center; there is learning, experimenting, taking inspiration from games and improving step by step.",
          tags: ["learn", "build", "improve", "repeat"],
        },
      ],
    },
    projects: {
      eyebrow: "Lab Space",
      title: "Projects and Ideas",
      body: "This is not just a finished-project showcase; it is a small production space where I keep what I learn, what I try and the ideas I may grow later.",
      tooltipIntro: "Hover over the tags to see short technology notes.",
      items: [
        {
          status: "live",
          title: "Personal Portfolio v1",
          key: "layout",
          visual: "interface",
          body: "A personal website with scroll-based color transitions, TR/EN support, fixed navigation and geek mode. First goal: introduce myself better.",
          tags: ["Next.js", "React", "Tailwind", "JavaScript"],
        },
        {
          status: "idea",
          title: "Game / Book / Series Journal",
          key: "library",
          visual: "game",
          body: "A small personal archive idea for tracking games, books and shows with ratings, notes and categories.",
          tags: ["UI", "LocalStorage", "Data Model"],
        },
        {
          status: "idea",
          title: "Hardware Repair Notes",
          key: "wrench",
          visual: "circuit",
          body: "A mini logging system for gamepad or small electronics repairs, structured around problem, cause and solution.",
          tags: ["Hardware", "Documentation", "Archive"],
        },
        {
          status: "later",
          title: "GPA / Course Tracker",
          key: "calculator",
          visual: "interface",
          body: "A simple but useful student tool to keep courses, credits and grades organized and make semester goals clearer.",
          tags: ["JavaScript", "Form", "Calculation"],
        },
      ],
    },
    roadmap: {
      eyebrow: "quest log",
      title: "Future Goals",
      body: "Like a developer roadmap: quests waiting to be completed, skills waiting to be unlocked and long-term boss fights.",
      active: "active",
      locked: "locked",
      quests: [
        {
          span: "short term",
          status: "aktif",
          key: "book",
          title: "Strengthen web development",
          body: "Build stronger work with Next.js, databases, API logic and clean interfaces.",
        },
        {
          span: "short term",
          status: "aktif",
          key: "zap",
          title: "Improve English and communication",
          body: "Knowing technical topics is not enough; explaining them well matters too. Diction and English come in here.",
        },
        {
          span: "mid term",
          status: "aktif",
          key: "cpu",
          title: "Hardware + software mini project",
          body: "Build a small but real system that controls a physical device with software.",
        },
        {
          span: "mid term",
          status: "kilitli",
          key: "gamepad",
          title: "Personal tracking app",
          body: "Create a small dashboard to track games, books, series/movies and goals in one place.",
        },
        {
          span: "long term",
          status: "kilitli",
          key: "rocket",
          title: "A product real users can touch",
          body: "Not just a demo; a designed, usable and published project built end-to-end.",
        },
        {
          span: "long term",
          status: "kilitli",
          key: "trophy",
          title: "Open-source and team experience",
          body: "Build with communities, raise code quality and get deeper into real team workflows.",
        },
      ],
    },
    geek: {
      eyebrow: "mini terminal",
      title: "Turn On Geek Mode",
      body: "A small terminal area that does not take over the whole site. A few commands reveal short info, skills and contact details.",
      buttonOn: "geek mode: on",
      buttonOff: "geek mode: off",
      terminalLabel: "Geek mode terminal",
      terminalTitle: "halil@portfolio: ~",
      close: "Close terminal",
      bootLines: [
        "$ sudo ./geek_mode --activate",
        "[ ok ] checking coffee level... enough",
        "[ ok ] loading redstone circuits...",
        "[ ok ] opening MMORPG quest log...",
        "[ ok ] syncing book / series / movie list.",
        "[ ok ] connecting gamepad drivers...",
        "> hello, world. I'm Halil.",
        "> code, tinker, learn, improve, repeat.",
        "geek_mode: ONLINE ✓",
      ],
      commands: {
        placeholder: "type: help",
        list: ["help", "whoami", "skills --list", "ls projects", "cat about.txt", "contact", "clear", "sudo hire-me"],
        unknown: "Command not found. Tiny hint: try typing help.",
        responses: {
          help: "Commands: help, whoami, skills --list, ls projects, cat about.txt, contact, clear, sudo hire-me",
          whoami: "Halil Efe Kutlu — Computer Engineering student. Code, hardware, story-driven games and tinkering mode enabled.",
          "skills --list": "JavaScript / React / Next.js / Tailwind / Python / Java / C# / basic hardware curiosity / problem solving",
          "ls projects": "portfolio-v1  game-book-series-journal.idea  hardware-repair-notes.idea  gpa-tracker.later",
          "cat about.txt": "Not a classic CV; more like someone who learns, experiments, debugs errors and enjoys making things work.",
          contact: "The WhatsApp button is fixed at the bottom right. Mail: halilefekutlu01@gmail.com",
          "sudo hire-me": "permission granted: Halil joined the quest. Bonus trait: fast learning + tinkering energy.",
        },
      },
    },
    contact: {
      eyebrow: "Contact",
      title: "Let's build something together",
      body: "I am here for new ideas, collaborations, project talks or simply saying hello.",
      email: "Send Email",
      copyright: "Halil Efe Kutlu · Balıkesir University",
      backToTop: "Back to top",
    },
    whatsapp: {
      label: "Message on WhatsApp",
      text: "Hi Halil, I'm writing through your website.",
    },
  },
};
